### ISSUE TITLE
status: Status | str = Status.UNKNOWN TypeError: unsupported operand type(s) for |: 'EnumMeta' and 'type'

### ISSUE THREAD

**Issue by denischergicalo** [PCiunkiewicz/loc-abs#1]
I was using python 3.9 and installed all libraries in requirements.txt but I still get the error:

Traceback (most recent call last):
  File "C:\Users\denis\PycharmProjects\EmotionOptimization\launch.py", line 16, in <module>
    from simulation.model import simulate_model, SIRModel
  File "C:\Users\denis\PycharmProjects\EmotionOptimization\simulation\model.py", line 18, in <module>
    from simulation.agent import SIRAgent, Agent
  File "C:\Users\denis\PycharmProjects\EmotionOptimization\simulation\agent.py", line 14, in <module>
    from simulation.types.agent import Status, AgentTime, AgentSpec
  File "C:\Users\denis\PycharmProjects\EmotionOptimization\simulation\types\agent.py", line 48, in <module>
    class AgentState:
  File "C:\Users\denis\PycharmProjects\EmotionOptimization\simulation\types\agent.py", line 50, in AgentState
    status: Status | str = Status.UNKNOWN
TypeError: unsupported operand type(s) for |: 'EnumMeta' and 'type'

**Comment by PCiunkiewicz** [comment]
Python 3.9 is not supported, please use Python 3.10.

**Comment by denischergicalo** [comment]
Ok, for python 3.10 everything really works without problems.
